// This file is auto-generated by @hey-api/openapi-ts

export type AiConnectorDefaults = {
  translator: string;
  throttle: number;
  model: string;
  systemPrompt: string;
  prompt: string;
  maxTokens: number;
  temperature: number;
  frequencyPenalty: number;
  presencePenalty: number;
  nucleusSamplingFactor: number;
  split: boolean;
  asHtml: boolean;
};

export type AiTranslatorView = {
  name: string;
  alias: string;
};

export type AiTranslateDefaultsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/umbraco/tm-ai/api/v1/Defaults";
};

export type AiTranslateDefaultsResponses = {
  /**
   * OK
   */
  200: AiConnectorDefaults;
};

export type AiTranslateDefaultsResponse =
  AiTranslateDefaultsResponses[keyof AiTranslateDefaultsResponses];

export type AiTranslateTranslatorsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/umbraco/tm-ai/api/v1/Translators";
};

export type AiTranslateTranslatorsResponses = {
  /**
   * OK
   */
  200: Array<AiTranslatorView>;
};

export type AiTranslateTranslatorsResponse =
  AiTranslateTranslatorsResponses[keyof AiTranslateTranslatorsResponses];

export type ClientOptions = {
  baseUrl: "http://localhost:46796" | (string & {});
};
