// This file is auto-generated by @hey-api/openapi-ts

export type AiTranslatorView = {
  name: string;
  alias: string;
};

export type AiTranslateTranslatorsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/umbraco/tm-ai/api/v1/Translators";
};

export type AiTranslateTranslatorsResponses = {
  /**
   * OK
   */
  200: Array<AiTranslatorView>;
};

export type AiTranslateTranslatorsResponse =
  AiTranslateTranslatorsResponses[keyof AiTranslateTranslatorsResponses];

export type ClientOptions = {
  baseUrl: "http://localhost:11591" | (string & {});
};
